In [12]:

import pandas as pd

In [13]:
df = pd.read_csv("fragrantica.csv", encoding="iso-8859-1", sep=";") 
df.head()

,url,Perfume,Brand,Country,Gender,Rating Value,Rating Count,Year,Top,Middle,Base,Perfumer1,Perfumer2,mainaccord1,mainaccord2,mainaccord3,mainaccord4,mainaccord5
0,https://www.fragrantica.com/perfume/xerjoff/ac...,accento-overdose-pride-edition,xerjoff,Italy,unisex,"1,42",201,2022.0,"fruity notes, aldehydes, green notes","bulgarian rose, egyptian jasmine, lily-of-the-...","eucalyptus, pine",unknown,NaN,rose,woody,fruity,aromatic,floral
1,https://www.fragrantica.com/perfume/jean-paul-...,classique-pride-2024,jean-paul-gaultier,France,women,"1,86",70,2024.0,"yuzu, citruses","orange blossom, neroli","musk, blonde woods",unknown,NaN,citrus,white floral,sweet,fresh,musky
2,https://www.fragrantica.com/perfume/jean-paul-...,classique-pride-2023,jean-paul-gaultier,France,unisex,"1,91",285,2023.0,"blood orange, yuzu","neroli, orange blossom","musk, white woods",natalie gracia-cetto,quentin bisch,citrus,white floral,sweet,fresh spicy,musky
3,https://www.fragrantica.com/perfume/bruno-bana...,pride-edition-man,bruno-banani,Germany,men,"1,92",59,2019.0,"guarana, grapefruit, red apple","walnut, lavender, guava","vetiver, benzoin, amber",unknown,NaN,fruity,nutty,woody,tropical,NaN
4,https://www.fragrantica.com/perfume/jean-paul-...,le-male-pride-collector,jean-paul-gaultier,France,men,"1,93",632,2020.0,"mint, lavender, cardamom, artemisia, bergamot","caraway, cinnamon, orange blossom","vanilla, sandalwood, amber, cedar, tonka bean",francis kurkdjian,NaN,aromatic,warm spicy,fresh spicy,cinnamon,vanilla

In [14]:
# define the columns to keep
columns_to_keep = ["Gender", "Rating Value", "mainaccord1", "mainaccord2", "mainaccord3"]

# keep only the specified columns
df = df[columns_to_keep]

In [15]:
df.head()

   Gender Rating Value mainaccord1   mainaccord2  mainaccord3
0  unisex         1,42        rose         woody       fruity
1   women         1,86      citrus  white floral        sweet
2  unisex         1,91      citrus  white floral        sweet
3     men         1,92      fruity         nutty        woody
4     men         1,93    aromatic    warm spicy  fresh spicy

In [16]:
# replace commas with dots in 'Rating Value'
df['Rating Value'] = df['Rating Value'].str.replace(',', '.')

# convert 'Rating Value' from string to float
# use pd.to_numeric to convert strings to numbers
df["Rating Value"] = pd.to_numeric(df["Rating Value"])
df.head()

   Gender  Rating Value mainaccord1   mainaccord2  mainaccord3
0  unisex          1.42        rose         woody       fruity
1   women          1.86      citrus  white floral        sweet
2  unisex          1.91      citrus  white floral        sweet
3     men          1.92      fruity         nutty        woody
4     men          1.93    aromatic    warm spicy  fresh spicy

In [17]:
#count "NaN" values 
df.isna().sum()

Gender            0
Rating Value      0
mainaccord1       0
mainaccord2      13
mainaccord3     114
dtype: int64

In [18]:
#save the new table perfumes.csv file
df.to_csv("parfums.csv", index=False, sep=',')
df = pd.read_csv("parfums.csv")
df.head()

   Gender  Rating Value mainaccord1   mainaccord2  mainaccord3
0  unisex          1.42        rose         woody       fruity
1   women          1.86      citrus  white floral        sweet
2  unisex          1.91      citrus  white floral        sweet
3     men          1.92      fruity         nutty        woody
4     men          1.93    aromatic    warm spicy  fresh spicy

In [19]:
df.count()

Gender          24063
Rating Value    24063
mainaccord1     24063
mainaccord2     24050
mainaccord3     23949
dtype: int64

In [20]:
#count "NaN" values 
df.isna().sum()

Gender            0
Rating Value      0
mainaccord1       0
mainaccord2      13
mainaccord3     114
dtype: int64

In [21]:
# replace NaN in 'mainaccord2' and 'mainaccord3' with 'mainaccord1'
df["mainaccord2"] = df["mainaccord2"].fillna(df["mainaccord1"])
df["mainaccord3"] = df["mainaccord3"].fillna(df["mainaccord1"])
df.isna().sum()

Gender          0
Rating Value    0
mainaccord1     0
mainaccord2     0
mainaccord3     0
dtype: int64

In [22]:
# create a binary column for success: 1 if 'Rating Value' >= 4.0 (success), 0 otherwise
df["is_high_rated"] = (df["Rating Value"] >= 4.0).astype(int)
df

,Gender,Rating Value,mainaccord1,mainaccord2,mainaccord3,is_high_rated
0,unisex,1.42,rose,woody,fruity,0
1,women,1.86,citrus,white floral,sweet,0
2,unisex,1.91,citrus,white floral,sweet,0
3,men,1.92,fruity,nutty,woody,0
4,men,1.93,aromatic,warm spicy,fresh spicy,0
...,...,...,...,...,...,...
24058,women,4.81,white floral,ozonic,fresh,1
24059,unisex,4.81,rose,amber,fresh spicy,1
24060,unisex,4.85,green,aromatic,citrus,1
24061,unisex,4.86,fruity,sweet,oud,1
24062,men,4.93,aromatic,woody,warm spicy,1