In [255]:

import pandas as pd

In [256]:
df = pd.read_csv("fragrantica.csv", encoding="iso-8859-1", sep=";") 
df.head()

,url,Perfume,Brand,Country,Gender,Rating Value,Rating Count,Year,Top,Middle,Base,Perfumer1,Perfumer2,mainaccord1,mainaccord2,mainaccord3,mainaccord4,mainaccord5
0,https://www.fragrantica.com/perfume/xerjoff/ac...,accento-overdose-pride-edition,xerjoff,Italy,unisex,"1,42",201,2022.0,"fruity notes, aldehydes, green notes","bulgarian rose, egyptian jasmine, lily-of-the-...","eucalyptus, pine",unknown,NaN,rose,woody,fruity,aromatic,floral
1,https://www.fragrantica.com/perfume/jean-paul-...,classique-pride-2024,jean-paul-gaultier,France,women,"1,86",70,2024.0,"yuzu, citruses","orange blossom, neroli","musk, blonde woods",unknown,NaN,citrus,white floral,sweet,fresh,musky
2,https://www.fragrantica.com/perfume/jean-paul-...,classique-pride-2023,jean-paul-gaultier,France,unisex,"1,91",285,2023.0,"blood orange, yuzu","neroli, orange blossom","musk, white woods",natalie gracia-cetto,quentin bisch,citrus,white floral,sweet,fresh spicy,musky
3,https://www.fragrantica.com/perfume/bruno-bana...,pride-edition-man,bruno-banani,Germany,men,"1,92",59,2019.0,"guarana, grapefruit, red apple","walnut, lavender, guava","vetiver, benzoin, amber",unknown,NaN,fruity,nutty,woody,tropical,NaN
4,https://www.fragrantica.com/perfume/jean-paul-...,le-male-pride-collector,jean-paul-gaultier,France,men,"1,93",632,2020.0,"mint, lavender, cardamom, artemisia, bergamot","caraway, cinnamon, orange blossom","vanilla, sandalwood, amber, cedar, tonka bean",francis kurkdjian,NaN,aromatic,warm spicy,fresh spicy,cinnamon,vanilla

In [257]:
# replace commas with dots in 'Rating Value'
df['Rating Value'] = df['Rating Value'].str.replace(',', '.')

# convert 'Rating Value' from string to float and 'Rating Count' to integer
# use pd.to_numeric to convert strings to numbers
df["Rating Value"] = pd.to_numeric(df["Rating Value"])
df["Rating Count"] = pd.to_numeric(df["Rating Count"])

In [ ]:
# count total # of parfums
print("# parfums:", len(df))

# count total parfums with more than 50 Rating Count
print("# parfums with Rating Count >= 50:", len(df[df["Rating Count"] >= 50]))

# keep only parfums with Rating Count >= 50
df = df[df["Rating Count"] >= 50]

# parfums: 24063
# parfums with Rating Count >= 50: 18958

In [259]:
# define the relevant columns to keep
columns_to_keep = ["Gender", "Rating Value", "mainaccord1", "mainaccord2", "mainaccord3"]

# keep only the specified columns
df = df[columns_to_keep]

In [260]:
df.head()

   Gender  Rating Value mainaccord1   mainaccord2  mainaccord3
0  unisex          1.42        rose         woody       fruity
1   women          1.86      citrus  white floral        sweet
2  unisex          1.91      citrus  white floral        sweet
3     men          1.92      fruity         nutty        woody
4     men          1.93    aromatic    warm spicy  fresh spicy

In [ ]:
#save the new table perfumes.csv file
df.to_csv("parfums.csv", index=False, sep=",")
df = pd.read_csv("parfums.csv")
df.head()

   Gender  Rating Value mainaccord1   mainaccord2  mainaccord3
0  unisex          1.42        rose         woody       fruity
1   women          1.86      citrus  white floral        sweet
2  unisex          1.91      citrus  white floral        sweet
3     men          1.92      fruity         nutty        woody
4     men          1.93    aromatic    warm spicy  fresh spicy

In [262]:
df.count()

Gender          18958
Rating Value    18958
mainaccord1     18958
mainaccord2     18948
mainaccord3     18879
dtype: int64

In [263]:
#count "NaN" values 
df.isna().sum()

Gender           0
Rating Value     0
mainaccord1      0
mainaccord2     10
mainaccord3     79
dtype: int64

In [264]:
# missing values management 
# replace NaN in 'mainaccord2' and 'mainaccord3' with 'mainaccord1'
df["mainaccord2"] = df["mainaccord2"].fillna(df["mainaccord1"])
df["mainaccord3"] = df["mainaccord3"].fillna(df["mainaccord1"])
df.isna().sum()

Gender          0
Rating Value    0
mainaccord1     0
mainaccord2     0
mainaccord3     0
dtype: int64

In [ ]:
# create a binary column for success: 1 if Rating Value >= 4.0 (success), 0 otherwise
df["is_high_rated"] = (df["Rating Value"] >= 4.0).astype(int)
df

,Gender,Rating Value,mainaccord1,mainaccord2,mainaccord3,is_high_rated
0,unisex,1.42,rose,woody,fruity,0
1,women,1.86,citrus,white floral,sweet,0
2,unisex,1.91,citrus,white floral,sweet,0
3,men,1.92,fruity,nutty,woody,0
4,men,1.93,aromatic,warm spicy,fresh spicy,0
...,...,...,...,...,...,...
18953,men,4.72,amber,warm spicy,woody,1
18954,unisex,4.73,oud,rose,leather,1
18955,women,4.74,warm spicy,floral,powdery,1
18956,men,4.75,musky,ozonic,aquatic,1
18957,men,4.75,warm spicy,vanilla,woody,1

In [266]:
# EDA - unique values in each main accord
total = df.iloc[: , -4:-1].nunique()
print(total)

print("unique values in mainaccord1:", sorted(df['mainaccord1'].unique()))
print("unique values in mainaccord2:", sorted(df['mainaccord2'].unique()))
print("unique values in mainaccord3:", sorted(df['mainaccord3'].unique()))

mainaccord1    61
mainaccord2    69
mainaccord3    70
dtype: int64
unique values in mainaccord1: ['aldehydic', 'almond', 'amber', 'animalic', 'anis', 'aquatic', 'aromatic', 'balsamic', 'beeswax', 'cacao', 'caramel', 'champagne', 'cherry', 'chocolate', 'cinnamon', 'citrus', 'coca-cola', 'coconut', 'coffee', 'earthy', 'floral', 'fresh', 'fresh spicy', 'fruity', 'green', 'herbal', 'honey', 'industrial glue', 'iris', 'lactonic', 'lavender', 'leather', 'marine', 'metallic', 'mineral', 'mossy', 'musky', 'nutty', 'oriental', 'oud', 'ozonic', 'patchouli', 'powdery', 'rose', 'salty', 'savory', 'smoky', 'soapy', 'soft spicy', 'sweet', 'tobacco', 'tropical', 'tuberose', 'vanilla', 'vinyl', 'violet', 'warm spicy', 'whiskey', 'white floral', 'woody', 'yellow floral']
unique values in mainaccord2: ['aldehydic', 'almond', 'amber', 'animalic', 'anis', 'aquatic', 'aromatic', 'balsamic', 'beeswax', 'brown scotch tape', 'cacao', 'camphor', 'cannabis', 'caramel', 'champagne', 'cherry', 'chocolate', 'cinnamon', 'citrus', 'clay', 'coca-cola', 'coconut', 'coffee', 'earthy', 'floral', 'fresh', 'fresh spicy', 'fruity', 'gourmand', 'green', 'herbal', 'honey', 'iris', 'lactonic', 'lavender', 'leather', 'marine', 'metallic', 'mineral', 'mossy', 'musky', 'nutty', 'oily', 'oud', 'ozonic', 'patchouli', 'powdery', 'rose', 'rum', 'salty', 'sand', 'savory', 'smoky', 'soapy', 'soft spicy', 'spicy', 'sweet', 'tobacco', 'tropical', 'tuberose', 'vanilla', 'violet', 'vodka', 'warm spicy', 'whiskey', 'white floral', 'wine', 'woody', 'yellow floral']
unique values in mainaccord3: ['alcohol', 'aldehydic', 'almond', 'amber', 'animalic', 'anis', 'aquatic', 'aromatic', 'balsamic', 'beeswax', 'bitter', 'cacao', 'camphor', 'cannabis', 'caramel', 'champagne', 'cherry', 'chocolate', 'cinnamon', 'citrus', 'coca-cola', 'coconut', 'coffee', 'conifer', 'earthy', 'floral', 'fresh', 'fresh spicy', 'fruity', 'green', 'herbal', 'honey', 'iris', 'lactonic', 'lavender', 'leather', 'marine', 'metallic', 'mineral', 'mossy', 'musky', 'nutty', 'oud', 'ozonic', 'patchouli', 'plastic', 'powdery', 'rose', 'rum', 'salty', 'sand', 'savory', 'smoky', 'soft spicy', 'sour', 'spicy', 'sweet', 'tobacco', 'tropical', 'tuberose', 'vanilla', 'vinyl', 'violet', 'vodka', 'warm spicy', 'whiskey', 'white floral', 'wine', 'woody', 'yellow floral']

In [267]:
def group_accord(accord):
    # Convert to lowercase to handle variations
    accord = str(accord).lower()
    
    # Citrus (Hespéridée) 
    if any(keyword in accord for keyword in [ 'citrus', 'fresh', 'ozonic', 'aquatic', 'marine', 'champagne', 'coca-cola', 'salty']):
        return 'Citrus'
    
    # Floral (Fleuri) 
    elif any(keyword in accord for keyword in ['floral', 'rose', 'iris', 'violet', 'tuberose', 'white floral', 'yellow floral', 'powdery', 'aldehydic']):
        return 'Floral'
    
    # Woody (Boisé)
    elif any(keyword in accord for keyword in ['woody', 'oud', 'patchouli', 'earthy', 'mossy', 'conifer', 'paper']):
        return 'Woody'
    
    # Fougère - Add herbal and aromatic for more examples
    elif any(keyword in accord for keyword in ['green','lavender', 'herbal', 'fresh spicy', 'camphor', 'cannabis']):
        return 'Fougère'
    
    # Chypre - Add resinous and earthy
    elif any(keyword in accord for keyword in ['mossy', 'earthy', 'mineral', 'clay', 'sand']):
        return 'Chypre'
    
    # Oriental - Keep sweet fruits and gourmand
    elif any(keyword in accord for keyword in ['vanilla', 'amber', 'musky', 'balsamic', 'sweet', 'gourmand', 'caramel', 'chocolate', 'coconut', 'honey', 'rum', 'whiskey', 'wine', 'tobacco', 'leather', 'smoky', 'spicy', 'warm spicy', 'soft spicy', 'anis', 'cinnamon', 'nutty', 'almond', 'beeswax', 'oily', 'lactonic', 'tropical', 'fruity', 'cherry', 'cacao', 'coffee', 'savory', 'animalic']):
        return 'Oriental'
    
    # Aromatic - Only for specific fresh/aquatic notes
    else:  # Includes green, fresh, aquatic, ozonic
        return 'Aromatic'

# grouping
df['accord1_group'] = df['mainaccord1'].apply(group_accord)
df['accord2_group'] = df['mainaccord2'].apply(group_accord)
df['accord3_group'] = df['mainaccord3'].apply(group_accord)

# Show distribution
'''
print("\nDistribuição de accord1_group:")
print(df['accord1_group'].value_counts())
print("\nDistribuição de accord2_group:")
print(df['accord2_group'].value_counts())
print("\nDistribuição de accord3_group:")
print(df['accord3_group'].value_counts())
'''

'\nprint("\nDistribuição de accord1_group:")\nprint(df[\'accord1_group\'].value_counts())\nprint("\nDistribuição de accord2_group:")\nprint(df[\'accord2_group\'].value_counts())\nprint("\nDistribuição de accord3_group:")\nprint(df[\'accord3_group\'].value_counts())\n'

In [268]:
df

,Gender,Rating Value,mainaccord1,mainaccord2,mainaccord3,is_high_rated,accord1_group,accord2_group,accord3_group
0,unisex,1.42,rose,woody,fruity,0,Floral,Woody,Oriental
1,women,1.86,citrus,white floral,sweet,0,Citrus,Floral,Oriental
2,unisex,1.91,citrus,white floral,sweet,0,Citrus,Floral,Oriental
3,men,1.92,fruity,nutty,woody,0,Oriental,Oriental,Woody
4,men,1.93,aromatic,warm spicy,fresh spicy,0,Aromatic,Oriental,Citrus
...,...,...,...,...,...,...,...,...,...
18953,men,4.72,amber,warm spicy,woody,1,Oriental,Oriental,Woody
18954,unisex,4.73,oud,rose,leather,1,Woody,Floral,Oriental
18955,women,4.74,warm spicy,floral,powdery,1,Oriental,Floral,Floral
18956,men,4.75,musky,ozonic,aquatic,1,Oriental,Citrus,Citrus
18957,men,4.75,warm spicy,vanilla,woody,1,Oriental,Oriental,Woody